### ISSUE TITLE
Dietas: error al abrir la pagina

### ISSUE THREAD

**Issue by DHurtado714** [RodrigoTeran/natgas#65]
Al abrir la pagina sale este error: 

```
ERROR
"[object Object]" is not valid JSON
SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at http://localhost:3000/static/js/bundle.js:7017:36
    at Array.map (<anonymous>)
    at Dietas (http://localhost:3000/static/js/bundle.js:6956:47)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:42041:22)
    at updateFunctionComponent (http://localhost:3000/static/js/bundle.js:44923:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:46635:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:31633:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:31677:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:31734:35)
```

![image](https://user-images.githubusercontent.com/81983296/232273102-2ba9c1d2-438c-4916-8088-605fffc12ee8.png)

**Comment by DHurtado714** [comment]
Lo que ocurrio es que el JSON.parse no funciona bien. No tenemos una solucion exacta pero al menos a mi me funciona
